name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: macos-latest
            name: macOS
          - os: windows-2019
            name: Windows-10
          - os: windows-2022
            name: Windows-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --break-system-packages -r requirements.txt pylint
      - name: Lint with pylint
        run: |
          pylint .
      - name: Lint with flake8
        run: |
          flake8 main.py test.py
      - name: Run tests
        run: |
          pytest -q

  arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm python python-pip git
          pip install -r requirements.txt pylint
      - name: Lint with pylint
        run: |
          pylint .
      - name: Lint with flake8
        run: |
          flake8 main.py test.py
      - name: Run tests
        run: |
          pytest -q
